sudo: true
language: node_js
node_js:
  - 'node'
  - '9'
os: osx
install:
  - npm install -g node-gyp
  - npm install -g electron-packager
  - npm install
  - electron-packager . minerstat --overwrite --platform=darwin --arch=x64 --icon=asset/logo.icns --prune=true --out=release-builds